import AppLayout from "@/components/admin/layout/app-layout";
import { AppSidebar } from "@/components/admin/layout/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Hanuman } from "next/font/google";

export const metadata: Metadata = {
  title: "Bonjour",
  description: "Generated by create next app",
};

const hanuman = Hanuman({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["khmer", "latin"],
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider className={hanuman.className}>
      <AppSidebar />
      <AppLayout>{children}</AppLayout>
    </SidebarProvider>
  );
}
